### ISSUE TITLE
working combination of versions of libav, untrunc and gcc version

### ISSUE THREAD

**Issue by prof7bit** [ponchio/untrunc#109]
I have been trying for the last 3 hours to make it compile with all current and old versions of Ubuntu that have working docker images and at least two versions of libav i found mentioned here and none of them will compile.

What on earth are you guys using to compile this?

maybe it would be a good idea to make some kind of **build script** that downloads the exact versions of dependencies that are known to work, maybe even download the needed compiler and build it first if necessary and then build it with all needed compiler flags.

or at least please write in the readme which revision of untrunc has been known to compile and work with which revision of libav. For example the current master of untrunc (as of ec8e4173f0d48c6925412f4eb395deda45875ac3) **will not** work with ibav-12.3 as described in the readme, I finally got it to compile after 3 hours but when I run it it throws:

    Reading: /mnt/f2s2/backup/q/2018-05-18/1.mp4
    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
    Abgebrochen

I'm giving up.

**Comment by erikarvstedt** [comment]
Try the [nix](https://nixos.org/nix/) package for a perfectly deterministic build:
`nix-env -i untrunc`

Here's the nix [package definition](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/video/untrunc/default.nix).

**Comment by brandon-dacrib** [comment]
There is also a dockerfile available now to solve for these things.
