### ISSUE TITLE
FATAL error config.h - no such file or directory exists

### ISSUE THREAD

**Issue by onni82** [ponchio/untrunc#113]
Tried to compile untrunc on Ubuntu Desktop 18.04, but I get this error message
track.cpp:46:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.

How can I fix this?
Thank you

**Comment by erikarvstedt** [comment]
The `config.h` referenced here belongs to `libav`. It gets created by running `configure` in the `libav` source dir.

**Comment by onni82** [comment]
Where can I find the libav source dir if I installed via official Ubuntu/Debian rep?
I installed by doing: sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev

**Comment by onni82** [comment]
I manually installed libav instead, but then I get another error message like this:
/usr/bin/x86_64-linux-gnu-ld: cannot find -lz
collect2: error: ld returned 1 exit status

**Comment by onni82** [comment]
Okay, it worked when I just didn't use -lz in my command, even though the instructions told me to use it.
