### ISSUE TITLE
BUG: Travis-CI no longer tests the integration of PRs (commit f004f9c)

### ISSUE THREAD

**Issue by Hacklin** [ponchio/untrunc#118]
BUG: Travis-CI no longer tests the integration of Pull Request or any other branch except for master!
(Due to commit f004f9c)

Commit f004f9c hijacked Travis-CI to build a Docker executable from git master.
Travis-CI should be used to test the integration of any changes to the source, including PRs.
As it stands, the current setup just happens to test changes to master only.

- The Dockerfile used in the service docker in .travis.yml should be used to create a build environment in which to test the integration.
- To create Docker executables it's probably better to use a separate git repository.
For Docker executables see also:
    1. Debian-based Docker exe: https://github.com/bylevel/docker_untrunc.git
    (Uses an embedded builder Docker container to reduce the final executable size.)
    2. ArchLinux-based Docker exe: https://github.com/mooyoul/docker-untrunc.git
    3. Ubuntu:12.04-based Docker exe: https://github.com/synctree/docker-untrunc.git
- People may want to create a Docker executable based on their own distro (Fedora, CentOS, SuSE).

Suggestions:
- Update the `Docker container` instructions in the `README.md`:
    1. Add a comment that you must install the `docker` package first.
    2. Add a description on the usage of the docker `-v` option.
    Not everybody dumps files on their desktop.
    What to do when the files are in different directories?
- Mention the other Docker Untrunc projects in the `README.md`.
- Rename `Dockerfile` to `Dockerfile-ubuntu`, so one can easily add Docker containers based on different distros.  Or maybe, even put it in a new `dockers` subdirectory.
- Add a `.dockerignore` file.
- And above all else, use Travis-CI for integration testing!
You can use Travis-CI to **test** if the Docker-Untrunc executable can be build (and upload the successful build to a Docker Registry), but only when Travis-CI is used to test git **master** itself.  There is no need to unnecessary increase the test time for PRs and non-master branches.

**Comment by brandon-dacrib** [comment]
This is a bit confusing. You said:

> BUG: Travis-CI no longer tests the integration of Pull Request or any other branch except for master!

and then you said: 

> You can use Travis-CI to test if the Docker-Untrunc executable can be build (and upload the successful build to a Docker Registry), but only when Travis-CI is used to test git master itself. There is no need to unnecessary increase the test time for PRs and non-master branches.

Which do you want? Travis-CI to run on all branches, just PRs or just master?

**Comment by Hacklin** [comment]
Travis-CI runs on every source push (be it a PR or a git push to any branch in `untrunc.git`).
AFAIK, you cannot change this (in the free version).

In the `.travis.yml` you can tell using `TRAVIS_*` environment variables, if Travis-CI was run for a PR or not, and for which branch.
So you can program Travis-CI to only update the Docker-executable if the source push is to git master.
However, Travis-CI must always first do a test build to see if the source push is valid.

**Comment by Hacklin** [comment]
This is fixed by PR #124
