### ISSUE TITLE
Compile error: incompatible types in assignment

### ISSUE THREAD

**Issue by EQWorry** [ponchio/untrunc#158]
Compiling untrunc as per instructions for other systems (Debian), cannot get past the following error. Ideas/corrections much appreciated. Instruction

`g++ -o untrunc -I./libav-12.3 file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L./libav-12.3/libavformat -lavformat -L./libav-12.3/libavcodec -lavcodec -L./libav-12.3/libavresample -lavresample -L./libav-12.3/libavutil -lavutil -lpthread -lz`

leads to

```
atom.cpp: In constructor ‘Atom::Atom()’:
atom.cpp:104:67: error: incompatible types in assignment of ‘const char [1]’ to ‘char [5]’
 Atom::Atom() : start(0), length(0), name(""), head(""), version("") { }
                                                                   ^
atom.cpp:104:67: error: incompatible types in assignment of ‘const char [1]’ to ‘char [4]’
atom.cpp:104:67: error: incompatible types in assignment of ‘const char [1]’ to ‘char [4]’
```

**Comment by anthwlock** [comment]
A possible solution is to use `std::string` instead of `char[]`, as it's done [here](https://github.com/anthwlock/untrunc).
