### ISSUE TITLE
can I repair a courrupted mov file using this on 

### ISSUE THREAD

**Issue by vipinbeni** [ponchio/untrunc#17]
please help me i want to repair corrupt mov file using this on windows / mac can i do this using this

pls help me ....

thanks.

**Comment by vipinbeni** [comment]
hi please tell me  can i do using this

**Comment by ponchio** [comment]
I don't know if someone managed to compile it on windows, someone surely did on mac.
Just send me the files (ponchio@gmail.com, use something like dropbox) and I will see what I can do.
