### ISSUE TITLE
Prediction is not allowed in AAC-LC

### ISSUE THREAD

**Issue by grospo** [ponchio/untrunc#171]
Hi!

I'm trying this tool on my broken video (truncated because the power got off). Unfortunately, when I launch it I get this error:
Reading: .***.MP4
Opening: ***.MP4
Repair: ***.MP4
Track 0 codec: mp4a
mp4a: Success for no particular reason....
[aac @ 0x210c140] Prediction is not allowed in AAC-LC.
Duration: 0

Invalid length: -1052488119. Wrong match in track: 0.
Track 1 codec: avc1
avc1: Failed for no particular reason.
Found 0 packets.

Saving to: ***_fixed.mp4
Track 0 (mp4a): duration: 0 timescale: 32000
Adjusting track duration to movie timescale: New duration: 0 timescale: 60000.
Track 1 (avc1): duration: 0 timescale: 60000
Adjusting track duration to movie timescale: New duration: 0 timescale: 60000.
Movie duration: 0 timescale: 60000

Does anyone have an idea why this happens??

Thank you in advance!

**Comment by ponchio** [comment]
Hi,
  no idea. It just look like the tool is starting from the wrong place in
the file to look up for packets.
If you send me the files I will have a look at them... I'm curious. (
ponchio@gmail.com).

**Comment by ponchio** [comment]
The problem was a 'free' blocks in the middle of the stream and multiple mdat.
Committed a solution or the first problem... the second is harder to fix.
