### ISSUE TITLE
source file size 763MB, output file size 3MB

### ISSUE THREAD

**Issue by catamountlin** [ponchio/untrunc#195]
hi, i try to fix a .mp4 file that created by Captrue(an open source screen recording software, base on ffmpeg), 
it is broken because of the machine power gone and the recording is not stopped normally

ffmpeg file check: moov atom not found
untrunc fix result: source file size 763MB, output file size 3MB

how can i fix it? thk

> Saving to: ../../Documents/Captura/2020-07-21-18-14-09.mp4_fixed.mp4
> Track 0 (mp4a): duration: 738304 timescale: 44100
> Adjusting track duration to movie timescale: New duration: 16742 timescale: 1000.
> Track 1 (avc1): duration: 256512 timescale: 15360
> Adjusting track duration to movie timescale: New duration: 16700 timescale: 1000.
> Movie duration: 16742 timescale: 1000

**Comment by ponchio** [comment]
Hi, most probably the program failed to rebuild the sample structure after
a few samples. I definitely need to improve error reporting.

Could you send me the movies so I can look for the problem? (
ponchio@gmail.com)
