### ISSUE TITLE
where is codec_apch.cpp ?

### ISSUE THREAD

**Issue by gisforgirard** [ponchio/untrunc#201]
https://github.com/ponchio/untrunc/blob/b2838559c0807f95bbb3b5f4791842edb3ee5dac/untrunc.pro#L35

**Comment by gisforgirard** [comment]
well, i got the most recent "logging" branch to compile with this change(s): https://github.com/ponchio/untrunc/pull/202

**Comment by ponchio** [comment]
Forgot to add it. Fixed, sorry.
