### ISSUE TITLE
Can I fix the h265 file？

### ISSUE THREAD

**Issue by jinbo1996** [ponchio/untrunc#210]
Can I fix the h265 file？I encountered a flashback when repairing h265 files

**Comment by ponchio** [comment]
Just send me the samples, I will see what's the problem. (ponchio@gmail.com
).

**Comment by jinbo1996** [comment]
https://user-images.

**Comment by jinbo1996** [comment]
https://user-images.githubusercontent.com/55678358/108795533-ab6b3580-75c1-11eb-8344-65c7549dfd61.mp4

**Comment by jinbo1996** [comment]
https://user-images.githubusercontent.com/55678358/108795571-bde56f00-75c1-11eb-8dbe-26afdf6408c0.mp4

**Comment by jinbo1996** [comment]
https://user-images.githubusercontent.com/55678358/108795584-c50c7d00-75c1-11eb-8b4b-2821bb99876d.mp4

**Comment by jinbo1996** [comment]
https://user-images.githubusercontent.com/55678358/108795596-cb9af480-75c1-11eb-9abe-9b6ef2b7442a.mp4

**Comment by ponchio** [comment]
Now you can. Thanks for the samples!

**Comment by Jack-Leey** [comment]
hello ,could this fix h265 mov format 's video file?
