### ISSUE TITLE
What files could be removed after compiling?

### ISSUE THREAD

**Issue by Symbian9** [ponchio/untrunc#213]
- **Version:** https://github.com/ponchio/untrunc/commit/f85925d9203debe0ca537552f7f2afcef6077e58
- **OS:** Debian 10 buster

I compiled itself now so what files should be kept & what files could be removed from `./untrunc-master/` after success build of `./untrunc` binary?

1. `./untrunc` (57.9 Mb) — main binary required to keep (*yes, this should be NOT removed*);
2. `./libav-12.3/` (**451.7 MiB**) — folder with codecs:
2.1. `./libav-12.3/avconv` (61.0 Mb) — keep OR remove this binary?
2.2. `./libav-12.3/avprobe` (59.8 Mb) — keep OR remove this binary?
2.3. `./libav-12.3/libavcodec//libavcodec.a` (107.7 Mb) — keep or remove this binary?
2.4. `./libav-12.3/libavformat/libavformat.a` (30.1 Mb) — keep or remove this binary?
2.5. `./libav-12.3/libavutil/libavutil.a/` (1.2 Mb) — keep or remove this binary?
2.6. `./libav-12.3/libavfilter/libavfilter.a` (2.9 Mb) — keep or remove this binary?
2.7. `./libav-12.3/libswscale/libswscale.a` (3.5 Mb) — keep or remove this binary?
2.8. `./libav-12.3/libavresample/libavresample.a/` (586.8 Kb) — keep or remove this binary?
2.9. etc.

Would be it OK keeping only `./untrunc` binary and removing of all of the rest?

**Comment by ponchio** [comment]
You only need the executable untrunc, and if you "strip" it (man strip),
it's 10 MB.

By the way, the command "ldd" shows you the shared library dependencies.
