### ISSUE TITLE
only 90kb,Bytes Not matched:3.16MiB(97.3%)

### ISSUE THREAD

**Issue by jinbo1996** [ponchio/untrunc#214]
There are two h264 files, Please help me see why the fix failed.Thank you.
[file.zip](https://github.com/ponchio/untrunc/files/6119923/file.zip)

**Comment by ponchio** [comment]
Did you use the current version of the code? (given the name of the file, it looks like an old version of the code).
Anyway, it works.

https://user-images.githubusercontent.com/2636523/110774037-a6fb7980-825d-11eb-8bb7-08d65322c774.mp4

**Comment by jinbo1996** [comment]
Thank you for your reply, I'm using code from the anthwlock/untrunc project,not this project

**Comment by ponchio** [comment]
The two codebase work on basically the same principle and code, but there are some difference on the strategy used to detect the start of the data section and euristic algorithms when it is not possible to reliably detect the length of some packets.

It might happen than one works on certain videos and the other does not. There are countless different way in which a video can be corrupted, and really complex to try to cover all of them.
