### ISSUE TITLE
unable repair mp4 file.

### ISSUE THREAD

**Issue by suyeol** [ponchio/untrunc#215]
Hi everyone,

I tried to recover mp4 files using your untranc.

However, it was not recovered.

_$ ./untrunc /path/OK.mp4 /path/NOTOK.mp4_

The following error occurred.

_Repair: /path/NOTOK.mp4
Mdat start: 1768505 end: 74120241
Offset:    1768505  begin: a8fdbdfd b7fdbafd
Unknown length, search for next beginning, guessed as: 0
Could not guess length of best match
Repair: /path/NOTOK.mp4
Mdat start: 1048584 end: 74120241
Offset:    1048584  begin: f9bd3f26 dfe10db6
Unknown length, search for next beginning, guessed as: 0
Could not guess length of best match
Repair: /path/NOTOK.mp4
Mdat start: 1048584 end: 74120241
Offset:    1048584  begin: f9bd3f26 dfe10db6
Unknown length, search for next beginning, guessed as: 0
Could not guess length of best match
Failed recovering the file
Saving to: /path/NOTOK_fixed.mp4
Track 0 (avc1): duration: 60429 timescale: 1000
Don;t know how to deal with variable sample size and variable number of samples per chunk. Trying with 1.
Track 1 (sowt): duration: 2664918 timescale: 44100
Movie duration: 60.429s with timescale: 1000_

Can you see what's wrong?

Files to download
https://drive.google.com/drive/folders/12QSwYe4rzlGBKkmO2-OkT7-ooAFxZvfR?usp=sharing

Thanks.

**Comment by ponchio** [comment]
I had a look at the files. The main problem is the sowt audio codec: it is just raw, unencoded audio data, and the length of the packets is variable (multiple of 2048 it seems, which could be of great help!).

It is somewhat difficult to guess (at least naively) where the video packets starts and even more where they end. 

Let me try to write a 'smarter' guesser and see if it succeeds (at least for your case).

**Comment by suyeol** [comment]
thank you for reply.

We look forward to seeing the revisions come up as soon as possible.

Thanks.

**Comment by ponchio** [comment]
The main problem is that in the middle of the packets some garbage is mixed. I made a dirty hack to detect garbage (entropy based ad hoc for this vide...), and could recover about 2/3 of the video, after that there are errors (wrong lengths, stretches of zeroes...) and recovering the content becomes a different game.

https://drive.google.com/file/d/16ziKv8hnd_3UAO3wIUW6m-x8vr4hCc0F/view?usp=sharing

**Comment by suyeol** [comment]
dear ponchio.

Thanks for the quick feedback.

Could you please commit the modified version?

In addition to this file, there are many other damaged files.

thanks

**Comment by ponchio** [comment]
I created a suyeol branch. Somewhat working but random garbage in the stream makes it really hard.
It would require a completely different algorimth to reliably recover audio and video.

**Comment by suyeol** [comment]
dear ponchio

I checked the branch you made well.
It has been confirmed that several files can be restored.

However, in one case, we have found that the program does not terminate.
Could you please tell me why?

A new video file has been attached.
The file name is NOTOKB.mp4.

**Files to download**
https://drive.google.com/drive/folders/12QSwYe4rzlGBKkmO2-OkT7-ooAFxZvfR?usp=sharing

I want NOTOK.mp4 and NOTOKB.mp4 both to be "untrunc" which can be restored.

Thank you so much for your help.

**Comment by ponchio** [comment]
I was assuming entropy for audio packets < 6. It happens that in that video, probably due to some white noise, entropy was 6.01

I have added a 'recovery' condition when the entropy guess is wrong. (can't fix the reverse: some garbage mistaken for audio, it would require some fourier analysis).
