### ISSUE TITLE
After the file is repaired, the audio is normal, and the video has problems

### ISSUE THREAD

**Issue by samll123** [ponchio/untrunc#221]
I have a problem, can you help me?
After the file is repaired, the video screen is stuck.
There are related documents in the attachment.

https://user-images.githubusercontent.com/38941206/119955651-d30fd680-bfd2-11eb-873a-f00976de37cd.mp4

https://user-images.githubusercontent.com/38941206/119955662-d5723080-bfd2-11eb-9b8b-d82446cc5d93.mp4

**Comment by ponchio** [comment]
The packets seems recognized correectly, the most probable cause is that the 2 videos has not be taken with the same exact compression parameters: aside for colorspace, width, height which probably are the same, there are some quantization parameters that are written in the movie header, and thus lost when the video was truncated.

Another possible reason is an incorrect subdivision of the video NAL (units of info such as a frame): there is a complex set of rules that defines where NAL must be grouped or split in packets, but I am at loss at what could be wrong. Sorry.

**Comment by samll123** [comment]
Okay thank you

**Comment by samll123** [comment]
Hello, I have an idea. While recording the file, I tried to copy a new file without writing the end of the copied file, so I would get a normal file and a wrong file. I tried to repair the files again using these two files, and the result was still the same as before.Do you have any other suggestions?

**Comment by ponchio** [comment]
This suggests that the problem is most probably in how the NAL are grouped,
as soon as I have some time I will try to guess what is the correct
strategy (I failed a few times already and can't find any decent
documentation),
at least with your video I have another test case...

**Comment by samll123** [comment]
Thanks

**Comment by ponchio** [comment]
Found the problem somewhere else :P 
Trying to fix video and audio sync problems when the timing per sample is variable (can't really be recovered, just estimated) got a negative timing.

**Comment by samll123** [comment]
I can't see that lssues




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Federico ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 晚上7:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ponchio/untrunc] After the file is repaired, the audio is normal, and the video has problems (#221)






关闭#221.

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by ponchio** [comment]
Last commit: drifting fix (attempt) is now optional and that what caused the video problem (which was recovered correctly, it's only the timing).
