### ISSUE TITLE
Could not create file for writing

### ISSUE THREAD

**Issue by RUN97** [ponchio/untrunc#223]
Hello,
After trying hard, i'm stuck with this message :
"avc1: no match because of nal type: 25
Found 81 packets
Could not create file for writing: /files/result.mp4_fixed.mp4"

Looking for a solution, I got the information underneath, however, I couldn't figure it out 
{  // Save to output file.
		clog << "Saving to: " << output_filename << '\n';
		File file;
		if(!file.create(output_filename))
			throw "Could not create file for writing: " + output_filename;

Is there any solution?

**Comment by ponchio** [comment]
Hi, most probably you do not have the permission to write to the /files/
folder  (assuming it exists...)

**Comment by RUN97** [comment]
I'm not used to Debian, there's smthg I'm missing and getting worse as now Debian is showing the message "Could not open file" jaj I'll take a rest and maybe try again later on. 
Thank you for the answer :)

**Comment by ponchio** [comment]
I have set up a service (http://untrunc.it) for anyone having problems with
compiling or using the code (sooner or later I might be able to create a
decent release system).
Might give it a try.

**Comment by przepompownia** [comment]
I would like to try to restore as much as possible from the file on a corrupted exfat FS. Reading such file causes remounting FS into read-only mode
```
[Thu Aug  5 20:03:07 2021] exFAT-fs (sdb1): error, broken FAT chain.                                                                                                                                                                            
[Thu Aug  5 20:03:07 2021] exFAT-fs (sdb1): Filesystem has been set read-only 
```
but untrunc attempts to write the result on the same FS. 

I did not found any parameter that allows to change the output directory.

**Comment by ponchio** [comment]
I have added the -o <filename> option to specify the target of the repaired filename.
