### ISSUE TITLE
You rock!

### ISSUE THREAD

**Issue by unfa** [ponchio/untrunc#224]
Thanks to you I was able to recover captured video files I've lost to my stupidity (as I used a known faulty card reader).
I've donated to express my gratitude and encourage further development of this amazing tool!

**Comment by ponchio** [comment]
Thanks!

**Comment by EnderShadow** [comment]
I'm so glad you made this! It saved a video I downloaded with youtube-dl that broke and wasn't able to be re-downloaded!

**Comment by eliazu** [comment]
a video of my 1st son seeing my 3rd new born son for the first time was damaged due to a camera app forced closed on my phone.
this tool recovered this unique video.
thank you so much.
