### ISSUE TITLE
Failed to recover MP4 with audio stream

### ISSUE THREAD

**Issue by bczhc** [ponchio/untrunc#242]
Hello!
I just tried to restore my screen recording video but failed, not knowing the reason. I then tried so much and I've found that in my case it seems videos with audio have trouble being recovered, it fails even if `broken.mp4` is directly truncated from `ok.mp4`, here's the details:

My screenrecords are done with:
```bash
parec --device=bluez-xxx.monitor | ffmpeg -f x11grab -framerate 30 -i "$DISPLAY" \
        -ar 44100 -ac 2 -f s16le -i pipe:0 \
        -c:v h264_nvenc \
        -profile:v high \
        -pix_fmt yuv420p \
        -b:v 0 \
        "$output_file"
```
It will record the display along with audio from `parec` stream. I just recorded a 20M sample video: [here](https://drive.google.com/file/d/1Io6QYDvMOg3p1gI1dIzbAuSEKUiHLFRj/view), let it be `original.mp4`. Then I made a broken video using: `dd if=original.mp4 of=truncated.mp4 bs=1M count=10`, and try to restore it:
```bash
untrunc original.mp4 truncated.mp4
```
Then I got these errors:
```
Reading: original.mp4
Repair: truncated.mp4
Mdat not found!
Processed: 4%
Backtracked enough!


Trying a different approach to locate mdat start
Repair: truncated.mp4
Processed: 4%
Processed: 51%
Backtracked enough!


Trying a different approach to locate mdat start
Repair: truncated.mp4
Mdat not found!
Processed: 43%
Backtracked enough!


Trying a different approach to locate mdat start
Repair: truncated.mp4
Mdat not found!
Processed: 4%
Processed: 51%
Backtracked enough!
Failed recovering the file
Saving to: truncated_fixed.mp4
```

Now with the mute video, `untrunc` can repair it:
```bash
ffmpeg -i original.mp4 -an -c:v copy original-an.mp4
dd if=original-an.mp4 of=truncated-an.mp4 bs=1M count=10
untrunc original-an.mp4 truncated-an.mp4
```

And I also tried another version of `untrunc` [anthwlock](https://github.com/anthwlock)/[untrunc](https://github.com/anthwlock/untrunc), but this can just repair my video.

Thanks

**Comment by bczhc** [comment]
Hi the `libav` submodule in this repo is pinned at the libav latest commit [c464278](https://github.com/libav/libav/commit/c4642788e83b0858bca449f9b6e71ddb015dfa5d), and I'm using this `libav` version.

But now I might have found the problem: I tried untrunc versions before [submodule was added](https://github.com/ponchio/untrunc/commit/f7783def74613c72bc90238fbab94aa1a248818f), using libav-v12.3 from https://libav.org/releases/libav-12.3.tar.xz but not the `libav` submodule, and it works. So it's really related to `libav` version, and the solution so far is to change `libav` submodule version from the latest [c46427](https://github.com/libav/libav/commit/c4642788e83b0858bca449f9b6e71ddb015dfa5d) to [tag-v12.3](https://github.com/libav/libav/commit/df744e3cf66548c9167ea857104a29d2ea92819e) ...

**Comment by SpiritInAShell** [comment]
I agree, I just downloaded that ```libav-12.3```, compiled it and dropped/replaced it into the untrunc source folder. Now I recovered a 3.8 GiB file with 59min with slight audio async (even with ```-d```) that I don't mind right now. With included libav i got only a 1.4MiB/10sec file (using the absolute same parameters and sample file)

> Hi the `libav` submodule in this repo is pinned at the libav latest commit [c464278](https://github.com/libav/libav/commit/c4642788e83b0858bca449f9b6e71ddb015dfa5d), and I'm using this `libav` version.
> 
> But now I might have found the problem: I tried untrunc versions before [submodule was added](https://github.com/ponchio/untrunc/commit/f7783def74613c72bc90238fbab94aa1a248818f), using libav-v12.3 from https://libav.org/releases/libav-12.3.tar.xz but not the `libav` submodule, and it works. So it's really related to `libav` version, and the solution so far is to change `libav` submodule version from the latest [c46427](https://github.com/libav/libav/commit/c4642788e83b0858bca449f9b6e71ddb015dfa5d) to [tag-v12.3](https://github.com/libav/libav/commit/df744e3cf66548c9167ea857104a29d2ea92819e) ...

**Comment by melyux** [comment]
Hey @ponchio, could you fix the submodule? Had the same problem as above and the workaround works.

**Comment by ponchio** [comment]
Thanks for spotting the submodule problem. I updated the submodule to version 12.3.
