### ISSUE TITLE
untrunc fails compile in mp4.cpp due to "expected expression" (M1 Mac, macOS Monterey 12.4)

### ISSUE THREAD

**Issue by djpinoy** [ponchio/untrunc#244]
Buongiorno,

Checking to see if anyone has had success compiling `untrunc` on an M1 Mac running macOS Monterey 12.4.

I followed the directions in the README and was able to successfully build `libav-12.3` from source.  However, when I attempt to use the provided command line to build `untrunc`, I get the following two errors in `mp4.cpp`:
```
mp4.cpp:707:44: error: expected expression
        std::sort(packets.begin(), packets.end(), [](const Match &m1, const Match &m2) { return m1.offset < m2.offset; });
                                                  ^
```

```
mp4.cpp:790:35: error: expected expression
        sort(group.begin(), group.end(), [](const Match &m1, const Match &m2) { return m1.chances > m2.chances; });
                                         ^
```

Both compile errors have to do with `sort()`, particularly the 3rd parameter and the use of `[]` so I'm still digging in to see what exactly it doesn't like.  But if anyone has any insight would appreciate it.  

For reference, the commandline I used was:
```
g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp codec_*.cpp codecstats.cpp codec.cpp mp4.cpp log.cpp -I./libav-12.3 -L./libav-12.3/libavformat -lavformat -L./libav-12.3/libavcodec -lavcodec -L./libav-12.3/libavresample -lavresample -L./libav-12.3/libavutil -lavutil -lpthread -lz -framework CoreFoundation -framework CoreVideo -framework VideoDecodeAcceleration -lbz2 -DOSX
```

Grazie mille!

**Comment by ponchio** [comment]
You could try to use the "convert" function of vlc to recover the whole
file. I don't remember if you can just copy the data or you have to
reencode video and audio (I bet on the first).

**Comment by djpinoy** [comment]
Yes - tried "convert" of `vlc` but still didn't work.

I found that with `ffmpeg` I was getting an `Unknown dref type` error in the logs when trying to read the file that had been processed by `untrunc`:
```
Opening an input file: ../paniki/DJI_0009_orig_untrunc.mp4.
[NULL @ 0x7f7b80004140] Opening '../paniki/DJI_0009_orig_untrunc.mp4' for reading
[file @ 0x7f7b80004540] Setting default whitelist 'file,crypto,data'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] ISO: File Type Major Brand: qt
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] Unknown dref type 0x73696c61 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] Processing st: 0, edit list 0 - media time: 0, duration: 3246243
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3246243 @ 3243
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3247244 @ 3244
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3248245 @ 3245
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3249246 @ 3246
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3250247 @ 3247
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3251248 @ 3248
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3252249 @ 3249
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3253250 @ 3250
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3254251 @ 3251
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7b80004140] drop a frame at curr_cts: 3255252 @ 3252
...
...
...
```

My guess is that the `unknown dref` causes all subsequent frames to be dropped (?) - but I'm not an expert yet with mp4...

After lots of experiments and google searches, was able to find this suggestion which allowed `ffmpeg` to ignore the issue and process the entire file completely:
https://video.stackexchange.com/questions/26391/ffmpeg-how-to-ignore-an-edit-list

Now the entire video (9m 45s) is playable and editable in FCPX.

Ancora, molte grazie!

**Comment by d3ibis** [comment]
Sorry to ask after a long time, @djpinoy which ffmpeg do u have ? from Homebrew or fro official website ? I'm trying to compile but getting errors on libav and passed it, now having errors while building untrunc

**Comment by djpinoy** [comment]
@d3ibis - no worries - isn't that what the internet is for? :P 

I believe I downloaded from the official website.  Here the details on the version I was using at the time:
```
% ./ffmpeg   
ffmpeg version N-107336-g59018254c7-tessus Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 27.100 / 57. 27.100
  libavcodec     59. 36.100 / 59. 36.100
  libavformat    59. 26.100 / 59. 26.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 42.100 /  8. 42.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

Let me know if there's anything else I can do to help.

**Comment by d3ibis** [comment]
@djpinoy ThanQ for ur reply, actually I fixed it by removing the ffmpeg I have and compile using `make FF_VER=3.3.9` & worked, then installed latest release from their site (for my personal use.

My issue now is untrunc is not fixing videos 100%, it repairs but giving me this result:

![Screenshot 2023-10-12 at 3 34 28 PM](https://github.com/ponchio/untrunc/assets/17270352/a3fd2b60-534a-4fdd-b15d-549576c8e833)

And I noticed a difference between the original corrupted file size (32MB) and the fixed one (5MB)!!!

btw, when I used an online service just to try, they gave me a demo for this 1 fixed with clear image, so I dnt know what I'm doing wrong...
