### ISSUE TITLE
Mdat not found--Only recovering 1MB of 4GB video!

### ISSUE THREAD

**Issue by mchen0037** [ponchio/untrunc#248]
Hello!

Would love to get some help with this! I was able to compile everything, but as some of the other issues have suggested, I'm unable to recover the full length of the video--I can see the first second of it and this is super promising! Would love some advice. Thank you!

```
Reading: ../working-video.mp4
Repair: ../broken-video.mp4
Mdat not found!
Backtracked enough!
Found 30 packets.
Found 29 chunks for avc1
Found 1 chunks for mp4a
Saving to: ../broken-video_fixed.mp4
```

**Comment by mchen0037** [comment]
I found a fork which actually ended up working:

https://github.com/anthwlock/untrunc

**Comment by ponchio** [comment]
Hi, the fork uses some different euristics to identify packets, and sometimes one works and not the other.

If are willing to send me the samples, working and not working, (I don't need the full 4GB, just say 30 or 40 MB), I can find the problem with my code and improve it. (double checking on anthwlock code).
