### ISSUE TITLE
ffmpeg compilation on snow leopard

### ISSUE THREAD

**Issue by roopa01** [ponchio/untrunc#27]
I build ffmpeg(2.7.1) on snow leopard following these 
https://trac.ffmpeg.org/wiki/CompilationGuide/MacOSX
 It has been build successfully generated following dylibs.

 /usr/local/Cellar/ffmpeg/2.7.1/bin/ffmpeg 
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.2.1 (GCC) (Apple Inc. build 5666) (dot 3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=gcc-4.2 --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfreetype --enable-libvorbis --enable-libvpx --enable-libfaac --enable-libass --enable-ffplay --enable-libfdk-aac --enable-libopus --enable-libquvi --enable-nonfree --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100

but when in build my source code using qmake &&make it gives error
  "_av_register_all", referenced from:
and warings
ld: warning: in /usr/local/lib/libavcodec.56.41.100.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /usr/local/lib/libavdevice.56.4.100.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /usr/local/lib/libavfilter.5.16.101.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /usr/local/lib/libavformat.56.36.100.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /usr/local/lib/libavutil.54.27.100.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
ld: warning: in /usr/local/lib/libswscale.3.1.101.dylib, file was built for unsupported file format which is not the architecture being linked (i386)
 kindly tell me what is the problem with this compilation.
 I tried with lower version of ffmpeg but same issue is there
Thanks

**Comment by gheja** [comment]
I am not familiar with building on a Mac but it seems that some of the files were built for x86/i386 and the rest for x64/amd64 architecture. I think you should try adding `-march=i386` to the g++ options.

**Comment by roopa01** [comment]
I tried  this but still same error massage. i also tried following link to build
http://hunterford.me/compiling-ffmpeg-on-mac-os-x
but no solution is there i don not what is problem .
Kindly help me.

**Comment by brandon-dacrib** [comment]
You should try the dockerized build which was recently merged into master.
