### ISSUE TITLE
Option to specify path for repaired destination file?

### ISSUE THREAD

**Issue by raisindetre** [ponchio/untrunc#286]
I'm working with very large files (10-bit DV captures of analogue Hi8 recordings using a DeckLink capture card). Some of these files run into 300GB. The file I'm trying to repair is about 230GB so it would be handy to be able to write the repaired file to a different disk volume than the input.

Does anyone know whether this is possible? I couldn't see any command flags providing for it.

**Comment by ponchio** [comment]
The command flag -o allows you to specify the full path of the output file.

./untrunc -o /data/recovered.mp4 good.mp4 bad.mp4

**Comment by nk9** [comment]
Sounds like this can be closed in that case.
