### ISSUE TITLE
ffmpeg compilation on windows XP

### ISSUE THREAD

**Issue by roopa01** [ponchio/untrunc#33]
Hi,

  I am using ffmpeg avcodec-55.dll , avdevice-55.dll,avfilter-3.dll,avformat-55.dll, avutil-52.dll,avutil.dll,postproc-52.dll, avfilter-4.dll ,swresample-0.dll,swscale-2.dll on windows XP using Qt 4.6.4. if i run .exe wchich is using these dll it  give following error. I have no idea about this error.
     Kindly help me to find out the problem. I attached the file showing this error.

"The procedure entry point OleflushClipBoard could not be located in the dynamic link library avformat-55.dll" 

![error](https://cloud.githubusercontent.com/assets/11420764/10131878/ff0c50de-65f0-11e5-931f-293c075dab24.jpg)

**Comment by sebix** [comment]
EOL anyway -> can be closed
