### ISSUE TITLE
Use of deprecated/already deleted functions

### ISSUE THREAD

**Issue by rohieb** [ponchio/untrunc#58]
When I try to compile revision 07be275f029274 on my system (ffmpeg 2.8.6), I get some deprecation warnings, and finally:

```
track.cpp: In member function ‘int Codec::getLength(unsigned char*, int)’:
track.cpp:204:40: error: ‘avcodec_alloc_frame’ was not declared in this scope
   AVFrame *frame = avcodec_alloc_frame();
                                        ^
```

[It seems](http://libav-user.ffmpeg.narkive.com/XHWftyiI/avcodec-alloc-frame-was-not-declared-in-this-scope) that the function is now named `av_frame_alloc`, when I replace it in the code, the build works.

Similar problems will probably happen in the future if the deprecation warnings are not taken care of. See the [full build output](https://gist.github.com/rohieb/854b27192374413561cd2892888fca22).

**Comment by kehugter** [comment]
This fork is patched:
https://github.com/chundongwang/untrunc

**Comment by ponchio** [comment]
Fixed.
