### ISSUE TITLE
unable to compile (Ubuntu)

### ISSUE THREAD

**Issue by AndKe** [ponchio/untrunc#78]
as per instructions;

```
andre@loke:~/Desktop/untrunc-master$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L/usr/local/lib -lavformat -lavcodec -lavutil
track.cpp:30:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS 1
 
In file included from /usr/include/c++/6/cstdint:41:0,
                 from /usr/include/c++/6/bits/char_traits.h:420,
                 from /usr/include/c++/6/string:40,
                 from track.h:25,
                 from track.cpp:21:
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 
track.cpp:31:0: warning: "__STDC_CONSTANT_MACROS" redefined
 #define __STDC_CONSTANT_MACROS 1
 
In file included from /usr/include/c++/6/cstdint:41:0,
                 from /usr/include/c++/6/bits/char_traits.h:420,
                 from /usr/include/c++/6/string:40,
                 from track.h:25,
                 from track.cpp:21:
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:7:0: note: this is the location of the previous definition
 #  define __STDC_CONSTANT_MACROS
 
track.cpp: In member function ‘int Codec::getLength(unsigned char*, int)’:
track.cpp:204:40: error: ‘avcodec_alloc_frame’ was not declared in this scope
   AVFrame *frame = avcodec_alloc_frame();
                                        ^

```

**Comment by FinKsu** [comment]
Try `sudo apt-get install unzip yasm g++
cd /tmp/
wget https://github.com/ponchio/untrunc/archive/master.zip
unzip master.zip
cd untrunc-master
wget http://libav.org/releases/libav-0.8.7.tar.xz
tar xvf libav-0.8.7.tar.xz
cd libav-0.8.7
./configure
make
cd ..
g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-0.8.7 -L./libav-0.8.7/libavformat -lavformat -L./libav-0.8.7/libavcodec -lavcodec -L./libav-0.8.7/libavutil -lavutil -lpthread -lz` instead. Hope it works for you!

**Comment by AndKe** [comment]
needed to install yasm to run ./configure, then I got:

~/untrunc-master$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-0.8.7 -L./libav-0.8.7/libavformat -lavformat -L./libav-0.8.7/libavcodec -lavcodec -L./libav-0.8.7/libavutil -lavutil -lpthread -lz
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

**Comment by FinKsu** [comment]
Remove the `-lz`

**Comment by AndKe** [comment]
thanks, that worked fine.  - maybe readme.md should be updated ?

**Comment by agebrock** [comment]
If you want to use -lz you need to install "lib32z1-dev" in that case...

**Comment by brandon-dacrib** [comment]
You should try the dockerized build that was recently merged into master
