### ISSUE TITLE
Won't compile under Fedora as per README instructions, what dependency might be missing at my end?

### ISSUE THREAD

**Issue by metaleap** [ponchio/untrunc#85]
Following your instructions, after a bunch of warnings the `g++` build step fails with:

    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:382: undefined reference to `avresample_is_open'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_frame':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:221: undefined reference to `avresample_is_open'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_init_resample':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:163: undefined reference to `avresample_open'
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:169: undefined reference to `avresample_convert'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_frame':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:236: undefined reference to `avresample_convert'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_flush_resample':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:118: undefined reference to `avresample_convert'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:414: undefined reference to `avresample_close'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_flush':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:616: undefined reference to `avresample_close'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_close':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:640: undefined reference to `avresample_free'
    ./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_init':
    ~/c/misc/libav-12.2/libavcodec/opusdec.c:704: undefined reference to `avresample_alloc_context'

**Comment by ponchio** [comment]
Forgot library avresample (-L./libav12.2/libavresample -lavresample). Sorry.
