### ISSUE TITLE
Compiling issue Ubuntu 17.10

### ISSUE THREAD

**Issue by bluecrocodile** [ponchio/untrunc#93]
hi, can you help me?
I'm on ubuntu 17.10. I followed the instructions for ubuntu, so after unzipping the file, when I run:

 g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L/usr/local/lib -lavformat -lavcodec -lavutil

I get:
....
track.cpp:46:10: fatal error: config.h: Datei oder Verzeichnis nicht gefunden
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.

thank you!

**Comment by sebix** [comment]
I have the same problem in openSUE Tumbleweed.

#82 includes the same error, `-lbz2` solved it there. Not for me. In the code can be found that the file is not used for libav version 56, but for all others:

https://github.com/ponchio/untrunc/blob/2259a050833da5edb97b8b82582d334e98bf05f9/track.cpp#L45

But I don't have the `h264dec.h`. I have libavcodec57, libavformat57 and libavutil55 here.

**Comment by sebix** [comment]
Does not work on trusty too:
https://travis-ci.org/sebix/untrunc/jobs/328667346

**Comment by sibrat** [comment]
I have the same problem in debian stretch:
```
track.cpp:46:20: fatal error: config.h: No such file or directory
 #include <config.h>
                    ^
compilation terminated.

```

**Comment by Hacklin** [comment]
Latest Untrunc uses an internal header file from Libav/FFmpeg.
So you must use the sources from Libav/FFmpeg to build Untrunc.
(see also #96 )

**Comment by brandon-dacrib** [comment]
I recommend using the docker build which was just merged to master and building in a container.
