### ISSUE TITLE
OS X El Capitan compile error

### ISSUE THREAD

**Issue by sparkiemarkman** [ponchio/untrunc#98]
I followed the instructions for OS X  and I get the following errors when I run g++

file.cpp:23:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
track.cpp:28:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
atom.cpp:10:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
mp4.cpp:285:46: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                track.codec.context = context->streams[i]->codec;
                                                           ^
./libav-12.2/libavformat/avformat.h:712:21: note: 'codec' has been explicitly
      marked deprecated here
    AVCodecContext *codec;
                    ^
1 warning generated.

Have done the following to the letter...

## Installing on other operating system (Manual libav installation)

Download the source code from GitHub at https://github.com/ponchio/untrunc and unzip the source code.
    
Download [libav, 12.2 version](http://libav.org/releases/libav-12.2.tar.xz) from [libav download page](http://libav.org/download.html) and unzip into the untrunc source code library. Then:

    cd untrunc-master

Build the library

    cd libav-12.2
    ./configure
    make
    cd ../

Build untrunc

    g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-12.2 -L./libav-12.2/libavformat -lavformat -L./libav-12.2/libavcodec -lavcodec -L./libav-12.2/libavresample -lavresample -L./libav-12.2/libavutil -lavutil -lpthread -lz

All good until I attempt g++

What am I doing wrong?

**Comment by elahmo** [comment]
Cant compile on High Sierra either.

**Comment by brandon-dacrib** [comment]
I recommend using the docker build that was recently merged into master.
